<?php

declare(strict_types=1);

namespace Tests\E2E;

use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Process\Process;

#[Group('e2e')]
final class WorktreeServiceVersioningTest extends TestCase
{
    use E2ETestHelper;

    /**
     * Default postgres version (main checkout uses this).
     * Source: App\Service\ServiceRegistry::SERVICE_TYPES['postgres']['defaultVersion']
     */
    private const string MAIN_PG_VERSION = '18.3';

    /**
     * Alternate postgres version pinned in the worktree's .dde/config.yml.
     * Must differ from MAIN_PG_VERSION and exist in ServiceRegistry::knownVersions.
     * Source: App\Service\ServiceRegistry::SERVICE_TYPES['postgres']['knownVersions']
     */
    private const string WORKTREE_PG_VERSION = '17';

    /**
     * Postgres credentials.
     * Source: App\Database\PostgresAdapter::getUsername() / getPassword().
     */
    private const string PG_USER = 'postgres';

    private const string PG_PASSWORD = 'postgres';

    private Filesystem $filesystem;

    private string $mainRepoDir;

    private string $worktreeDir;

    private bool $mainProjectStarted = false;

    public function testWorktreeRunsDifferentPostgresVersionThanMain(): void
    {
        $this->initProjectInMain();

        // 1. system:up once, then main project:up with default postgres (18.3)
        $result = $this->runConsoleJsonInDir($this->mainRepoDir, 'system:up', timeout: 180);
        $this->assertSame('ok', $result['status'], 'system:up should succeed');

        $result = $this->runConsoleJsonInDir($this->mainRepoDir, 'project:up', timeout: 180);
        $this->assertSame('ok', $result['status'], 'main project:up should succeed');
        $this->mainProjectStarted = true;

        // Wait for main postgres to be ready, then confirm it is the default version.
        $this->waitForPostgresContainer(self::MAIN_PG_VERSION);
        $mainVersionBefore = $this->queryPostgresVersion(self::MAIN_PG_VERSION);
        $this->assertStringStartsWith(self::MAIN_PG_VERSION, $mainVersionBefore, 'main postgres must report default version');

        // 2. Create worktree on branch "pg-upgrade" and pin a different postgres version
        $this->createWorktree('pg-upgrade');

        $worktreeConfigPath = $this->worktreeDir.'/.dde/config.yml';
        $originalYaml = file_get_contents($worktreeConfigPath);
        $this->assertIsString($originalYaml);

        // The config generated by `project:init --services=postgres` (no version suffix)
        // stores services as a bare scalar list:
        //
        //   services:
        //       - postgres
        //
        // To pin version 17 we rewrite the entry to the name/version map form:
        //
        //   services:
        //       -
        //           name: postgres
        //           version: '17'
        //
        // This matches the array-of-maps shape accepted by ProjectConfigDefinition.
        $rewrittenYaml = preg_replace(
            '/^(\s*-\s*)postgres\s*$/m',
            "$1\n            name: postgres\n            version: '".self::WORKTREE_PG_VERSION."'",
            $originalYaml,
        );

        $this->assertIsString($rewrittenYaml);
        $this->assertNotSame($originalYaml, $rewrittenYaml, 'config rewrite must have changed something — update the regex if the YAML shape changed');
        file_put_contents($worktreeConfigPath, $rewrittenYaml);

        // 3. Worktree project:up with the pinned alternate version (17)
        $result = $this->runConsoleJsonInDir($this->worktreeDir, 'project:up', timeout: 300);
        $this->assertSame('ok', $result['status'], 'worktree project:up with postgres:17 should succeed');

        // Wait for worktree postgres to be ready
        $this->waitForPostgresContainer(self::WORKTREE_PG_VERSION);

        // 4a. Worktree container reports the alternate version
        $worktreeVersion = $this->queryPostgresVersion(self::WORKTREE_PG_VERSION);
        $this->assertStringStartsWith(self::WORKTREE_PG_VERSION, $worktreeVersion, 'worktree must see alternate postgres version');

        // 4b. Main STILL sees its own version — no cross-contamination
        $mainVersionAfter = $this->queryPostgresVersion(self::MAIN_PG_VERSION);
        $this->assertSame($mainVersionBefore, $mainVersionAfter, 'main postgres version must not change when worktree comes up with a different version');

        $this->assertNotSame($mainVersionAfter, $worktreeVersion, 'main and worktree must resolve `postgres` to different containers');

        // 4c. Both per-project networks exist concurrently.
        //     The worktree network name is derived from basename($worktreeDir), which includes the
        //     random hex suffix of the temp dir, so we cannot hardcode it. Instead we:
        //       - assert the main network exists by exact name
        //       - assert a worktree-suffixed network exists (pattern: dde-services-e2e-pgver-<anything>)
        //       - capture the actual worktree network name for the "gone after down" assertion
        $networks = (new Process(['docker', 'network', 'ls', '--format', '{{.Name}}']))->mustRun()->getOutput();
        $this->assertMatchesRegularExpression('/\bdde-services-e2e-pgver\b/', $networks, 'main network must exist');
        $this->assertMatchesRegularExpression('/\bdde-services-e2e-pgver-\S+/', $networks, 'worktree network must exist');

        // Capture the actual worktree network name so we can assert it disappears after down
        $matched = preg_match('/\bdde-services-e2e-pgver-(\S+)/', $networks, $worktreeNetworkMatch);
        $this->assertSame(1, $matched, 'could not parse worktree network name from docker network ls output');
        $worktreeNetworkName = $worktreeNetworkMatch[0];

        // 4d. The canonical DNS alias `postgres` resolves to the correct version
        //     in each network. This is the actual mechanism the feature fixes:
        //     previously both postgres-18.3 and postgres-17 tried to claim
        //     `postgres` on the shared network, producing non-deterministic DNS.
        $mainAliases = $this->networkAliasesFor('dde-services-e2e-pgver', 'dde-postgres-'.self::MAIN_PG_VERSION);
        $this->assertContains(
            'postgres',
            $mainAliases,
            'main network must bind the canonical `postgres` alias to the default-version container',
        );

        $worktreeAliases = $this->networkAliasesFor($worktreeNetworkName, 'dde-postgres-'.self::WORKTREE_PG_VERSION);
        $this->assertContains(
            'postgres',
            $worktreeAliases,
            'worktree network must bind the canonical `postgres` alias to the alternate-version container',
        );

        // 5. Worktree teardown: removes only the worktree network; main stays reachable
        $result = $this->runConsoleJsonInDir($this->worktreeDir, 'project:down', timeout: 60);
        $this->assertSame('ok', $result['status'], 'worktree project:down should succeed');

        // Main postgres must still be up and reachable after worktree teardown
        $mainVersionAfterWorktreeDown = $this->queryPostgresVersion(self::MAIN_PG_VERSION);
        $this->assertSame($mainVersionBefore, $mainVersionAfterWorktreeDown, 'main postgres must survive worktree project:down');

        $networksAfterWorktreeDown = (new Process(['docker', 'network', 'ls', '--format', '{{.Name}}']))->mustRun()->getOutput();
        $this->assertMatchesRegularExpression('/\bdde-services-e2e-pgver\b/', $networksAfterWorktreeDown, 'main network must still exist after worktree down');
        $this->assertStringNotContainsString($worktreeNetworkName, $networksAfterWorktreeDown, 'worktree network must be gone after worktree down');

        // Tear down main
        $result = $this->runConsoleJsonInDir($this->mainRepoDir, 'project:down', timeout: 60);
        $this->assertSame('ok', $result['status'], 'main project:down should succeed');
        $this->mainProjectStarted = false;
    }

    private function initProjectInMain(): void
    {
        $result = $this->runConsoleJsonInDir($this->mainRepoDir, 'project:init', [
            '--name=e2e-pgver',
            '--services=postgres',
            '--shell=bash',
            '--force',
        ]);
        $this->assertSame('ok', $result['status'], 'project:init in main should succeed');

        (new Process(['git', 'add', '-A'], $this->mainRepoDir))->mustRun();
        (new Process(['git', 'commit', '-m', 'add dde config'], $this->mainRepoDir))->mustRun();
    }

    private function createWorktree(string $branch): void
    {
        $process = new Process(['git', 'checkout', '-b', $branch], $this->mainRepoDir);
        $process->run();
        $this->assertTrue($process->isSuccessful(), 'git checkout -b should succeed');

        $process = new Process(['git', 'checkout', 'main'], $this->mainRepoDir);
        $process->run();

        $this->worktreeDir = $this->mainRepoDir.'-wt-'.$branch;
        $process = new Process(['git', 'worktree', 'add', $this->worktreeDir, $branch], $this->mainRepoDir);
        $process->run();
        $this->assertTrue($process->isSuccessful(), 'git worktree add should succeed: '.$process->getErrorOutput());
    }

    /**
     * @param list<string> $args
     *
     * @return array<string, mixed>
     */
    private function runConsoleJsonInDir(string $dir, string $command, array $args = [], int $timeout = 120): array
    {
        $originalProjectDir = $this->projectDir;
        $this->projectDir = $dir;
        $result = $this->runConsoleJson($command, $args, $timeout);
        $this->projectDir = $originalProjectDir;

        return $result;
    }

    /**
     * Query postgres server_version from within the named container.
     * The web container does not have psql, so we exec directly into the postgres container.
     * Credentials: App\Database\PostgresAdapter::getUsername() / getPassword().
     */
    private function queryPostgresVersion(string $containerVersion): string
    {
        $containerName = 'dde-postgres-'.$containerVersion;
        $process = new Process([
            'docker', 'exec', $containerName,
            'psql', '-U', self::PG_USER, '-tAc', 'SHOW server_version',
        ]);
        $process->setEnv([
            'PGPASSWORD' => self::PG_PASSWORD,
        ]);
        $process->setTimeout(10);
        $process->mustRun();

        return trim($process->getOutput());
    }

    /**
     * Wait for a postgres container to become ready.
     * Uses a 120-second budget: 60 attempts × 2-second sleep.
     */
    private function waitForPostgresContainer(string $version, int $maxAttempts = 120): void
    {
        $containerName = 'dde-postgres-'.$version;

        for ($i = 0; $i < $maxAttempts; $i++) {
            $process = new Process(['docker', 'exec', $containerName, 'pg_isready', '-U', self::PG_USER]);
            $process->setTimeout(5);
            $process->run();

            if ($process->isSuccessful()) {
                return;
            }

            usleep(1_000_000);
        }

        $this->fail(sprintf('PostgreSQL container %s did not become ready within %d seconds', $containerName, $maxAttempts));
    }

    /**
     * Returns the canonical network aliases that $containerName has inside $networkName.
     * Uses `docker inspect <container>` and reads .NetworkSettings.Networks.<network>.Aliases,
     * which is the authoritative source for per-network aliases as set in docker-compose.
     *
     * @return list<string>
     */
    private function networkAliasesFor(string $networkName, string $containerName): array
    {
        $process = new Process([
            'docker', 'inspect', $containerName,
            '--format', '{{json .NetworkSettings.Networks}}',
        ]);
        $process->mustRun();

        /** @var array<string, array{Aliases?: list<string>}> $networks */
        $networks = json_decode($process->getOutput(), true, 512, JSON_THROW_ON_ERROR);

        if (!isset($networks[$networkName])) {
            return [];
        }

        return $networks[$networkName]['Aliases'] ?? [];
    }

    protected function setUp(): void
    {
        $this->filesystem = new Filesystem();
        $this->consolePath = dirname(__DIR__, 2).'/bin/console';

        $this->mainRepoDir = sys_get_temp_dir().'/dde-e2e-pgver-'.bin2hex(random_bytes(8));
        $this->filesystem->mkdir($this->mainRepoDir);

        $this->tempDataDir = sys_get_temp_dir().'/dde-e2e-pgver-data-'.bin2hex(random_bytes(8));
        $this->filesystem->mkdir($this->tempDataDir);

        $this->projectDir = $this->mainRepoDir;
        $this->worktreeDir = '';

        (new Process(['git', 'init', '-b', 'main'], $this->mainRepoDir))->mustRun();
        (new Process(['git', 'config', 'user.email', 'test@test.com'], $this->mainRepoDir))->mustRun();
        (new Process(['git', 'config', 'user.name', 'Test'], $this->mainRepoDir))->mustRun();
        (new Process(['git', 'config', 'commit.gpgsign', 'false'], $this->mainRepoDir))->mustRun();

        // A minimal docker-compose.yml: just a web service to satisfy project:up.
        // No DATABASE_URL in the compose file — the per-project network test does not
        // require env var rewriting, only network-level isolation.
        $this->filesystem->dumpFile($this->mainRepoDir.'/docker-compose.yml', implode("\n", [
            'services:',
            '  web:',
            '    image: registry.whatwedo.ch/whatwedo/docker-base-images/nginx-php:v2.11',
            '    volumes:',
            '      - ./:/var/www',
        ]));

        $this->filesystem->dumpFile($this->mainRepoDir.'/index.php', "<?php\necho 'pgver E2E test';\n");

        (new Process(['git', 'add', '-A'], $this->mainRepoDir))->mustRun();
        (new Process(['git', 'commit', '-m', 'initial'], $this->mainRepoDir))->mustRun();

        $this->runConsole('system:down', timeout: 60);
        $this->cleanupLeftoverContainers();
    }

    protected function tearDown(): void
    {
        if ($this->worktreeDir !== '' && is_dir($this->worktreeDir)) {
            $this->projectDir = $this->worktreeDir;
            $this->runConsole('project:down', timeout: 60);
        }

        if ($this->mainProjectStarted) {
            $this->projectDir = $this->mainRepoDir;
            $this->runConsole('project:down', timeout: 60);
        }

        $this->projectDir = $this->mainRepoDir;
        $this->runConsole('system:down', timeout: 60);

        if ($this->worktreeDir !== '' && is_dir($this->worktreeDir)) {
            (new Process(['git', 'worktree', 'remove', '--force', $this->worktreeDir], $this->mainRepoDir))->run();
        }

        $this->filesystem->remove($this->mainRepoDir);

        if ($this->worktreeDir !== '' && is_dir($this->worktreeDir)) {
            $this->filesystem->remove($this->worktreeDir);
        }

        $this->filesystem->remove($this->tempDataDir);
    }
}
