version: '3.8'

services:
    mailhog:
        image: mailhog/mailhog
        restart: unless-stopped
        command: -storage=maildir -maildir-path=/var/lib/mailhog
        environment:
            - VIRTUAL_HOST=mailhog.test
            - VIRTUAL_PORT=8025
        volumes:
            - ./../../data/mailhog/var/lib/mailhog:/var/lib/mailhog:delegated
        ports:
            - "127.0.0.1:1025:1025"
        hostname: mailhog
        domainname: test
        container_name: dde_mailhog

networks:
    default:
        name: dde
        external: true

volumes:
    ssh-agent_socket-dir:
        name: dde_ssh-agent_socket-dir
