version: '3.8'

services:
    mariadb:
        image: mariadb:10.11
        restart: unless-stopped
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./../../data/mariadb/var/lib/mysql:/var/lib/mysql:delegated
        hostname: mariadb
        domainname: test
        container_name: dde_mariadb


networks:
    default:
        name: dde
        external: true

volumes:
    ssh-agent_socket-dir:
        name: dde_ssh-agent_socket-dir
